apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: idp-kpt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: main
        image: nginx:stable-alpine3.19
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
  replicas: 2
